Adding better formatting to publish dialog for summaries.
wwfxuk/tk-multi-publish2 pull request #4
Opened 2019-11-01 12:40 UTC by Liametc

2019-11-01 13:18 UTC, j0yu requested changes
Maybe add a screenshot to this PR of the HTML changes

Personally, I think all this can probably be suggested back to Shotgun and let them choose whether they like it or not

2019-11-01 13:18 UTC, j0yu commented on .travis.yml
> +dist: xenial
Submit this back to Shotgun, adding the URL for official Travis Docs

Remove the commented out bits later on in this file

2019-11-01 13:18 UTC, j0yu commented on python/tk_multi_publish2/publish_tree_widget/tree_node_item.py
>          Creates summary of actions
Add docs for `level`

2019-11-04 10:16 UTC, Liametc commented
![image](https://user-images.githubusercontent.com/14952660/68113677-3798ab80-feec-11e9-8f47-764f446c65cb.png)

2019-11-04 10:29 UTC, Liametc commented
Just removed the travis fix, to make it it's own PR allowing me to separate this out and push to shotgun. this will fail the tests in the meantime until that pr is merged

2019-11-04 10:32 UTC, closed without merging