Inherited Descriptions for publish items
wwfxuk/tk-multi-publish2 pull request #9
Opened 2020-04-02 11:49 UTC by Liametc

### Added

- Allowing descriptions made on parent publish items to trickle down to children as long as they don't already have a comment.

### Changed

- Automatic formatting changes on file save

2020-04-02 13:22 UTC, j0yu approved these changes

2020-04-02 16:20 UTC, Liametc commented
@j0yu sorry mate, made some completely different changes. Can you look at this again please? Thanks

2020-04-03 00:42 UTC, j0yu requested changes
All good apart from that tiny change

2020-04-03 00:42 UTC, j0yu commented on python/tk_multi_publish2/dialog.py
> +        except Exception, error:
```suggestion
        except Exception as error:
```

2020-04-03 08:22 UTC, j0yu approved these changes

2020-04-03 08:35 UTC, merged